In [17]:
import pandas as pd 
import numpy as np
pd.set_option('display.max_columns', None)

bike = pd.read_csv('/Users/gopesh/Documents/Machine Learning/Bike Price predictor/CSV Files/bikes_data_cleaned.csv')
bike_og = pd.read_csv('/Users/gopesh/Documents/Machine Learning/Bike Price predictor/CSV Files/bikes_data_cleaned.csv')
bike.head()

,title,brand_name,model,bike_age,kilometer,fuel_type,owner,city,color,insurance,mileage_owner_reported,riding_range,cylinders,front_brake_type,rear_brake_type,tyre_type,fuel_tank_capacity,reserve_fuel_capacity,price,vehicle_type,is_electric,total_fuel_capacity
0,2011 Hero Honda Splendor Drum,Hero Honda,Splendor Drum,15,50000,Not Available,First,Bhopal,Black,Comprehensive,45.0,565.65404,1.0,Not Available,Not Available,Not Available,12.0,2.581667,10000.0,bike,0,14.581667
1,2021 Ducati Monster Standard,Ducati,Monster Standard,5,2700,Petrol,Second,Mumbai,Dark Stealth,Not Available,45.0,266.00000,2.0,Disc,Disc,Tubeless,14.0,3.500000,1050000.0,bike,0,17.500000
2,2022 Bajaj Pulsar Dual Channel ABS [2022],Bajaj,Pulsar Dual Channel ABS [],4,30009,Petrol,First,Kolkata,Brooklyn Black,Comprehensive,46.0,722.00000,1.0,Disc,Disc,Tubeless,14.0,2.800000,120000.0,bike,0,16.800000
3,2019 Yamaha FZ Single Channel ABS,Yamaha,FZ Single Channel ABS,7,50244,Petrol,First,Chennai,BLACK,Not Available,46.0,696.00000,1.0,Disc,Drum,Tubeless,12.0,1.892000,65000.0,bike,0,13.892000
4,2019 TVS Apache Carburetor ABS - Smart Xonnect,TVS,Apache Carburetor ABS - Smart Xonnect,7,28000,Petrol,First,Bhopal,Black,Not Available,38.0,551.00000,1.0,Disc,Disc,Tubeless,12.0,2.500000,80000.0,bike,0,14.500000

In [3]:
br = bike['brand_name'].value_counts().index

In [4]:
bike.drop([119 , 978 , 1294,1935,2092,2127,2168,2271,2340,170,242,1227,1394,1492,1900,1013 ,2082,2095,15 ,1680,2264,2312,2338,2413,1300,791,1116,1527] , inplace= True)

In [16]:
bike.to_csv('final.csv' , index=False)

In [14]:
import numpy as np

bike['kilometer'] = np.log1p(bike['kilometer'])

In [ ]:
bike_og.drop([119 , 978 , 1294,1935,2092,2127,2168,2271,2340,170,242,1227,1394,1492,1900,1013 ,2082,2095,15 ,1680,2264,2312,2338,2413,1300,791,1116,1527] , inplace= True)
bike_og.drop(columns=['total_fuel_capacity'] , inplace=True)

bike_og will remain as it is and changes will be made in bike dataset

In [35]:
bike_og[(bike_og['kilometer'] > 100000) & (bike_og['bike_age']<= 2)]

Empty DataFrame
Columns: [title, brand_name, model, bike_age, kilometer, fuel_type, owner, city, color, insurance, mileage_owner_reported, riding_range, cylinders, front_brake_type, rear_brake_type, tyre_type, fuel_tank_capacity, reserve_fuel_capacity, price, vehicle_type, is_electric]
Index: []

In [ ]:
# bike['km_per_year'] = bike['kilometer'] / (bike['bike_age']+1)
bike['km_per_year'].describe()

count     2555.000000
mean      4457.910866
std       4272.932884
min          1.071429
25%       2190.972222
50%       3666.666667
75%       5750.000000
max      89970.000000
Name: km_per_year, dtype: float64

In [63]:
bike.drop([1565 , 2355] , inplace=True)

In [90]:
def clean_model_name(name):
    import re
    
    # remove bracket content
    name = re.sub(r"\[.*?\]", "", name)
    
    # normalize spacing
    name = " ".join(name.split())
    
    return name

test1['model_clean'] = test1['model'].apply(clean_model_name)
test1['model'] = test1['model_clean']
test1.drop(columns=['model_clean'] , inplace=True)

### Clubbed various models together which were same but were treated differently because of some modifications

In [76]:
bike.drop(columns=['km_per_year'] , inplace=True)

In [91]:
test1 = pd.read_csv('/Users/gopesh/Documents/Machine Learning/Bike Price predictor/CSV Files/final.csv')
test1['model'].nunique()

771

In [86]:
bike.describe()

,bike_age,kilometer,mileage_owner_reported,riding_range,cylinders,fuel_tank_capacity,reserve_fuel_capacity,price,is_electric
count,2549.000000,2549.000000,2549.000000,2549.000000,2549.000000,2549.000000,2549.000000,2.549000e+03,2549.000000
mean,6.516673,30909.200078,42.361710,549.641808,1.002354,11.295332,2.070459,1.045111e+05,0.034131
std,4.524161,27144.339882,12.982221,168.900969,0.284328,3.538300,0.812103,1.047000e+05,0.181601
min,0.000000,42.000000,0.000000,65.000000,0.000000,0.000000,0.000000,6.000000e+03,0.000000
25%,3.000000,12000.000000,35.000000,471.000000,1.000000,10.000000,1.500000,4.800000e+04,0.000000
50%,5.000000,24500.000000,45.000000,565.654040,1.000000,12.000000,2.064000,7.800000e+04,0.000000
75%,9.000000,43000.000000,50.000000,669.600000,1.000000,13.000000,2.600000,1.400000e+05,0.000000
max,43.000000,351282.000000,75.000000,975.000000,4.000000,21.000000,4.500000,1.700000e+06,1.000000

In [97]:
test1[test1['brand_name'] == 'KTM']['model'].value_counts()

model
Duke Standard         49
RC Standard           21
Adventure Standard     8
RC GP Edition          5
Duke LCD Cluster       1
RC ABS                 1
Duke ABS               1
Name: count, dtype: int64

In [96]:
def clean_model_name(name):
    import re
    
    # remove bracket content
    name = re.sub(r"\[.*?\]", "", name)
    
    # normalize spacing
    name = " ".join(name.split())
    
    return name

test1['model_clean'] = test1['model'].apply(clean_model_name)
test1['model'] = test1['model_clean']
test1.drop(columns=['model_clean'] , inplace=True)

In [99]:
test1.to_csv('final.csv' , index=False)

In [100]:
test1.head()

,title,brand_name,model,bike_age,kilometer,fuel_type,owner,city,color,insurance,mileage_owner_reported,riding_range,cylinders,front_brake_type,rear_brake_type,tyre_type,fuel_tank_capacity,reserve_fuel_capacity,price,vehicle_type,is_electric
0,2011 Hero Honda Splendor Drum,Hero Honda,Splendor Drum,15,10.819798,Not Available,First,Bhopal,Black,Comprehensive,45.0,565.65404,1.0,Not Available,Not Available,Not Available,12.0,2.581667,10000.0,bike,0
1,2021 Ducati Monster Standard,Ducati,Monster Standard,5,7.901377,Petrol,Second,Mumbai,Dark Stealth,Not Available,45.0,266.00000,2.0,Disc,Disc,Tubeless,14.0,3.500000,1050000.0,bike,0
2,2022 Bajaj Pulsar Dual Channel ABS [2022],Bajaj,Pulsar Dual Channel ABS,4,10.309286,Petrol,First,Kolkata,Brooklyn Black,Comprehensive,46.0,722.00000,1.0,Disc,Disc,Tubeless,14.0,2.800000,120000.0,bike,0
3,2019 Yamaha FZ Single Channel ABS,Yamaha,FZ Single Channel ABS,7,10.824666,Petrol,First,Chennai,BLACK,Not Available,46.0,696.00000,1.0,Disc,Drum,Tubeless,12.0,1.892000,65000.0,bike,0
4,2019 TVS Apache Carburetor ABS - Smart Xonnect,TVS,Apache Carburetor ABS - Smart Xonnect,7,10.239996,Petrol,First,Bhopal,Black,Not Available,38.0,551.00000,1.0,Disc,Disc,Tubeless,12.0,2.500000,80000.0,bike,0

In [110]:
test1[test1['price'] > 400000][['brand_name' , 'title' , 'model' , 'tyre_type' ,'bike_age', 'price' , 'kilometer']]

,brand_name,title,model,tyre_type,bike_age,price,kilometer
1,Ducati,2021 Ducati Monster Standard,Monster Standard,Tubeless,5,1050000.0,7.901377
17,Benelli,2021 Benelli Leoncino Standard,Leoncino Standard,Tubeless,5,450000.0,8.389587
39,Royal Enfield,2022 Royal Enfield Classic Halcyon,Classic Halcyon,Tubed,4,412000.0,10.518700
130,Benelli,2022 Benelli TRK Standard,TRK Standard,Tubeless,4,450000.0,9.798183
172,Ducati,2018 Ducati Monster Standard,Monster Standard,Tubeless,8,550000.0,9.798183
484,Royal Enfield,2024 Royal Enfield Shotgun 650 Custom Pro,Shotgun 650 Custom Pro,Tubeless,2,445000.0,7.313887
533,Triumph,2023 Triumph Street Triple RS Standard,Street Triple RS Standard,Tubeless,3,1050000.0,9.012011
547,Aprilia,2024 Aprilia RS Standard,RS Standard,Tubeless,2,430000.0,8.987322
647,Benelli,2022 Benelli TRK Standard,TRK Standard,Tubeless,4,600000.0,9.615872
769,Ducati,2016 Ducati Monster Standard,Monster Standard,Tubeless,10,500000.0,9.998843
791,Royal Enfield,2024 Royal Enfield Shotgun 650 Custom Special,Shotgun 650 Custom Special,Tubeless,2,435000.0,8.419360
850,Royal Enfield,2025 Royal Enfield Continental GT Chrome,Continental GT Chrome,Tubed,1,410000.0,7.244942
885,Harley-Davidson,2019 Harley-Davidson Fat Boy 2024 Standard,Fat Boy 2024 Standard,Tubeless,7,1250000.0,7.155396
1334,Kawasaki,2023 Kawasaki Z Standard,Z Standard,Tubeless,3,900000.0,9.159152
1431,Royal Enfield,2026 Royal Enfield Continental GT Chrome,Continental GT Chrome,Tubed,0,450000.0,4.795791
1489,Aprilia,2024 Aprilia RS Standard,RS Standard,Tubeless,2,450000.0,8.987322
1524,Suzuki,2021 Suzuki V-Strom Standard,V-Strom Standard,Tubeless,5,720000.0,10.434145
1563,Aprilia,2024 Aprilia RS Quickshifter,RS Quickshifter,Tubeless,2,420000.0,9.210440
1851,Harley-Davidson,2016 Harley-Davidson Iron 883 Standard,Iron 883 Standard,Tubeless,10,700000.0,8.630700
1944,Harley-Davidson,2022 Harley-Davidson Fat Boy 2024 Standard,Fat Boy 2024 Standard,Tubeless,4,1700000.0,8.006701
2114,Ducati,2021 Ducati Diavel Standard,Diavel Standard,Tubeless,5,1700000.0,7.824446
2486,Aprilia,2024 Aprilia RS Standard,RS Standard,Tubeless,2,415000.0,8.268988

In [122]:
test1.to_csv('final.csv' , index=False)

In [ ]:
xtrain = pd.read_csv('/Users/gopesh/Documents/Machine Learning/Bike Price predictor/X_train.csv')
brand_avg = xtrain.groupby('brand_name')['price'].mean()
xtrain

brand_name
Aprilia            190333.333333
Ather              108000.000000
BMW                245178.571429
Bajaj               69788.002841
Benelli            312222.222222
Ducati             950000.000000
Harley-Davidson    548181.818182
Hero                58803.364706
Hero Honda          28976.190476
Honda               62535.326087
Jawa               149698.113208
KTM                159202.898551
Kawasaki           442500.000000
Mahindra            45166.666667
OLA                 92084.151515
Other               98178.571429
Revolt              81818.181818
Royal Enfield      177996.415771
Suzuki              64826.500000
TVS                 77130.323529
Triumph            296875.000000
UM                 101250.000000
Vespa               60727.272727
Yamaha              92182.726457
Yezdi              177789.473684
Name: price, dtype: float64